### ISSUE TITLE
Updating to MTGJSONv4

### ISSUE THREAD

**Issue by ZeldaZach** [clayadavis/card_codex#4]
Hey Clay,

MTGJSONv3 has been removed and MTGJSONv4 (4.2) is now live. I recommend you try updating to the new specs. All the info can be found at https://mtgjson.com/ 

If you have any Qs or suggestions, feel free to drop me a line :)

**Comment by clayadavis** [comment]
Thanks for the heads-up about the format change, @ZeldaZach :+1:

Everything is up-to-date.
