### ISSUE TITLE
Applications for EDH

### ISSUE THREAD

**Issue by jkaupanger** [clayadavis/card_codex#6]
Did you ever apply your program to EDH deck data?

Right now, I'm basically trying to recreate your work but with EDH decks. One thing that I realized that I'm having trouble with is identifying tribal decks. For Eldrazi, it's pretty easy to pick out because there're relatively few Eldrazi. For Elves, however, there are a LOT of different options that would still constitute "Elf Tribal".

Do you have any suggestions for tweaking hyperparameters to account for this? I'm new to statistics, topic modelling, and Python, lol

**Comment by clayadavis** [comment]
I haven't used EDH deck data to train models before, though it would be interesting. One model similar to what you're proposing is used by MTGGoldfish to assign a likely deck label like "Jund" or "Esper Control" given an arbitrary decklist.

I'm afraid I don't have much advice for your specific proposal, but maybe I just don't have enough info. I'd definitely encourage you to get the data and give it a shot though! Card Codex came from me just wanting to reacquaint myself with topic modeling before I hit the job market; side projects like this are a great way to learn a new skill.
